const CFG={TZ:"America/La_Paz",SHEET_ID:""};
function ss(){return CFG.SHEET_ID?SpreadsheetApp.openById(CFG.SHEET_ID):SpreadsheetApp.getActiveSpreadsheet()}
function sh(n){return ss().getSheetByName(n)}
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function uid(){return"P-"+Utilities.getUuid().slice(0,8).toUpperCase()}
function headers(s){return s.getRange(1,1,1,s.getLastColumn()).getValues()[0]}
function records(s){if(s.getLastRow()<2)return[];let h=headers(s);return s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues().map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function setup(){let defs={PRODUCTOS:["id","nombre","categoria","precio","descripcion","icon","activo","createdAt","updatedAt"],PEDIDOS:["id","createdAt","updatedAt","source","table","client","note","total","status","paymentStatus"],ITEMS:["orderId","productId","nombre","precio","qty"],CAJA:["id","date","status","opening","updatedAt"]};Object.entries(defs).forEach(([n,h])=>{let s=sh(n)||ss().insertSheet(n);s.clear();s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1)});seed();return"OK"}
function seed(){let s=sh("PRODUCTOS");if(s.getLastRow()>1)return;let t=new Date(),d=[["1","Empanada Mixta","Empanadas",8,"Carne, queso y especias.","ph-cookie",true,t,t],["2","Empanada de Queso","Empanadas",7,"Queso cremoso.","ph-cookie",true,t,t],["3","Pizza Familiar","Pizza",55,"Pizza para compartir.","ph-pizza",true,t,t],["4","Pizza Mixta","Pizza",48,"Jamón, queso y vegetales.","ph-pizza",true,t,t],["5","Hamburguesa Chura","Snacks",28,"Carne, queso y salsa especial.","ph-hamburger",true,t,t],["6","Papas Fritas","Snacks",15,"Crocantes.","ph-french-fries",true,t,t],["7","Coca Cola","Bebidas",10,"Bebida fría.","ph-coffee",true,t,t]];s.getRange(2,1,d.length,d[0].length).setValues(d)}
function products(){return records(sh("PRODUCTOS")).filter(p=>p.activo!==false&&String(p.activo)!=="FALSE").map(p=>({...p,precio:Number(p.precio||0)}))}
function orders(){let os=records(sh("PEDIDOS")),it=records(sh("ITEMS"));return os.reverse().map(o=>({...o,total:Number(o.total||0),items:it.filter(x=>String(x.orderId)===String(o.id)).map(x=>({id:x.productId,nombre:x.nombre,precio:Number(x.precio||0),qty:Number(x.qty||1)}))}))}
function doGet(e){try{let a=e.parameter.action||"dashboard";if(a==="products")return out({ok:true,products:products()});if(a==="order"){let o=orders().find(x=>String(x.id)===String(e.parameter.id));return out({ok:!!o,order:o||null})}return out({ok:true,products:products(),orders:orders()})}catch(err){return out({ok:false,error:String(err)})}}
function doPost(e){try{let p=JSON.parse(e.postData.contents||"{}");if(p.action==="createOrder")return create(p);if(p.action==="updateOrder")return update(p);if(p.action==="saveProduct")return saveProduct(p);if(p.action==="cash")return cash(p);return out({ok:false,error:"Acción desconocida"})}catch(err){return out({ok:false,error:String(err)})}}
function create(p){let id=uid(),t=new Date(),s=sh("PEDIDOS"),i=sh("ITEMS");s.appendRow([id,t,t,p.source||"customer",p.table||"",p.client||"Cliente",p.note||"",Number(p.total||0),"pending","unpaid"]);(p.items||[]).forEach(x=>i.appendRow([id,x.id||"",x.nombre||"",Number(x.precio||0),Number(x.qty||1)]));return out({ok:true,id})}
function update(p){let s=sh("PEDIDOS"),h=headers(s),rows=records(s),ic=h.indexOf("id")+1,sc=h.indexOf("status")+1,uc=h.indexOf("updatedAt")+1;for(let n=0;n<rows.length;n++)if(String(rows[n].id)===String(p.id)){s.getRange(n+2,sc).setValue(p.status);s.getRange(n+2,uc).setValue(new Date());return out({ok:true})}return out({ok:false,error:"Pedido no encontrado"})}
function saveProduct(p){let s=sh("PRODUCTOS"),h=headers(s),rs=records(s),id=p.id||Utilities.getUuid().slice(0,8);for(let n=0;n<rs.length;n++)if(String(rs[n].id)===String(id)){s.getRange(n+2,1,1,h.length).setValues([[id,p.nombre,p.categoria,Number(p.precio||0),"","ph-package",true,rs[n].createdAt||new Date(),new Date()]]);return out({ok:true,id})}s.appendRow([id,p.nombre,p.categoria,Number(p.precio||0),"","ph-package",true,new Date(),new Date()]);return out({ok:true,id})}
function cash(p){sh("CAJA").appendRow([Utilities.getUuid().slice(0,8),new Date(),p.status||"closed",Number(p.opening||0),new Date()]);return out({ok:true})}
